if (FML.isModLoaded("TConstruct") && Tcon_enabled) {
    NEI.override("TConstruct:toolRod", [0]);
    NEI.override("TConstruct:pickaxeHead", [0]);
    NEI.override("TConstruct:shovelHead", [0]);
    NEI.override("TConstruct:hatchetHead", [0]);
    NEI.override("TConstruct:binding", [0]);
    NEI.override("TConstruct:toughBinding", [0]);
    NEI.override("TConstruct:toughRod", [0]);
    NEI.override("TConstruct:heavyPlate", [0]);
    NEI.override("TConstruct:swordBlade", [0]);
    NEI.override("TConstruct:wideGuard", [0]);
    NEI.override("TConstruct:handGuard", [0]);
    NEI.override("TConstruct:fullGuard", [0]);
    NEI.override("TConstruct:crossbar", [0]);
    NEI.override("TConstruct:knifeBlade", [0]);
    NEI.override("TConstruct:frypanHead", [0]);
    NEI.override("TConstruct:signHead", [0]);
    NEI.override("TConstruct:chiselHeade", [0]);
    NEI.override("TConstruct:scytheBlade", [0]);
    NEI.override("TConstruct:broadAxeHead", [0]);
    NEI.override("TConstruct:excavatorHead", [0]);
    NEI.override("TConstruct:largeSwordBlade", [0]);
    NEI.override("TConstruct:hammerHead", [0]);
    NEI.override("TConstruct:arrowhead", [0]);
    NEI.override("TConstruct:fletching", [0]);
    NEI.override("TConstruct:ShurikenPart", [0]);
    NEI.override("TConstruct:BowLimbPart", [0]);
    NEI.override("TConstruct:CrossbowLimbPart", [0]);
    NEI.override("TConstruct:CrossbowBodyPart", [0]);
    NEI.override("TConstruct:BoltPart", [0]);
    NEI.hide("TConstruct:creativeModifier");
}

if (FML.isModLoaded("TConstruct") && Tcon_tools_enabled) {
    NEI.hide("TConstruct:pickaxe");
    NEI.hide("TConstruct:shovel");
    NEI.hide("TConstruct:hatchet");
    NEI.hide("TConstruct:broadsword");
    NEI.hide("TConstruct:longsword");
    NEI.hide("TConstruct:rapier");
    NEI.hide("TConstruct:dagger");
    NEI.hide("TConstruct:cutlass");
    NEI.hide("TConstruct:frypan");
    NEI.hide("TConstruct:battlesign");
    NEI.hide("TConstruct:mattock");
    NEI.hide("TConstruct:chisel");
    NEI.hide("TConstruct:lumberaxe");
    NEI.hide("TConstruct:cleaver");
    NEI.hide("TConstruct:scythe");
    NEI.hide("TConstruct:excavator");
    NEI.hide("TConstruct:dagger");
    NEI.hide("TConstruct:hammer");
    NEI.hide("TConstruct:battleaxe");
    NEI.hide("TConstruct:Shuriken");
    NEI.hide("TConstruct:ThrowingKnife");
    NEI.hide("TConstruct:Javelin");
    NEI.hide("TConstruct:ShortBow");
    NEI.hide("TConstruct:LongBow");
    NEI.hide("TConstruct:Crossbow");
    NEI.hide("TConstruct:ArrowAmmo");
    NEI.hide("TConstruct:BoltAmmo");
}

if (FML.isModLoaded("ExtraTiC") && ExtraTiC_enabled) {
    NEI.override("ExtraTiC:toolRod", [0]);
    NEI.override("ExtraTiC:pickaxeHead", [0]);
    NEI.override("ExtraTiC:shovelHead", [0]);
    NEI.override("ExtraTiC:hatchetHead", [0]);
    NEI.override("ExtraTiC:binding", [0]);
    NEI.override("ExtraTiC:toughBinding", [0]);
    NEI.override("ExtraTiC:toughRod", [0]);
    NEI.override("ExtraTiC:heavyPlate", [0]);
    NEI.override("ExtraTiC:swordBlade", [0]);
    NEI.override("ExtraTiC:wideGuard", [0]);
    NEI.override("ExtraTiC:handGuard", [0]);
    NEI.override("ExtraTiC:fullGuard", [0]);
    NEI.override("ExtraTiC:crossbar", [0]);
    NEI.override("ExtraTiC:knifeBlade", [0]);
    NEI.override("ExtraTiC:frypanHead", [0]);
    NEI.override("ExtraTiC:signHead", [0]);
    NEI.override("ExtraTiC:chiselHeade", [0]);
    NEI.override("ExtraTiC:scytheBlade", [0]);
    NEI.override("ExtraTiC:broadAxeHead", [0]);
    NEI.override("ExtraTiC:excavatorHead", [0]);
    NEI.override("ExtraTiC:largeSwordBlade", [0]);
    NEI.override("ExtraTiC:hammerHead", [0]);
    NEI.override("ExtraTiC:arrowhead", [0]);
    NEI.override("ExtraTiC:fletching", [0]);
    NEI.override("ExtraTiC:ShurikenPart", [0]);
    NEI.override("ExtraTiC:BowLimbPart", [0]);
    NEI.override("ExtraTiC:CrossbowLimbPart", [0]);
    NEI.override("ExtraTiC:CrossbowBodyPart", [0]);
    NEI.override("ExtraTiC:BoltPart", [0]);
}
